/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workshop6_7;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Gwi99
 */
public class ChatPanel extends javax.swing.JPanel {

    Socket socket = null;
    BufferedReader br = null;
    DataOutputStream os = null;
    OutputThread t = null;
    String sender = "";
    String receiver = "";

    public ChatPanel(Socket socket, String sender, String receiver) {
        initComponents();
        this.socket = socket;
        this.sender = sender;
        this.receiver = receiver;
        txtMessage.requestFocus();
        txtChatting.setEditable(false);

        try {
            br = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            os = new DataOutputStream(socket.getOutputStream());
            t = new OutputThread(socket, txtChatting, sender, receiver);
            t.start();

        } catch (IOException e) {
            error(e.getMessage());
        }

    }

    public ChatPanel() {
    }

    public JTextArea getTxtChatting() {
        return this.txtChatting;
    }

    public void error(String errMsg) {
        if (errMsg.contains("Connect reset")
                || errMsg.contains("Socket closed")) {
            JOptionPane.showMessageDialog(null, "Your peer is disconnected!");

        } else {
            JOptionPane.showMessageDialog(null, "ChatPanel: " + errMsg);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMessage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        JLabel1 = new javax.swing.JLabel();
        btnSendFile = new javax.swing.JButton();
        txtSourceFile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChatting = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(684, 550));

        PanelMessage.setPreferredSize(new java.awt.Dimension(638, 350));

        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });
        jScrollPane2.setViewportView(txtMessage);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        JLabel1.setText("Message");

        btnSendFile.setText("Send File");
        btnSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFileActionPerformed(evt);
            }
        });

        txtSourceFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSourceFileActionPerformed(evt);
            }
        });

        jLabel1.setText("Địa chỉ file:");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMessageLayout = new javax.swing.GroupLayout(PanelMessage);
        PanelMessage.setLayout(PanelMessageLayout);
        PanelMessageLayout.setHorizontalGroup(
            PanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMessageLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMessageLayout.createSequentialGroup()
                        .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(532, Short.MAX_VALUE))
                    .addGroup(PanelMessageLayout.createSequentialGroup()
                        .addGroup(PanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(PanelMessageLayout.createSequentialGroup()
                                .addComponent(btnSendFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelMessageLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelMessageLayout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMessageLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBrowse)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelMessageLayout.setVerticalGroup(
            PanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelMessageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMessageLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(PanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSourceFile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanelMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMessageLayout.createSequentialGroup()
                        .addComponent(btnBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        txtChatting.setColumns(20);
        txtChatting.setRows(5);
        jScrollPane1.setViewportView(txtChatting);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        if (txtMessage.getText().trim().length() == 0) {
            return;
        }
        try {
            os.writeBytes("*/#Messenger\n" + txtMessage.getText());
            os.write(13);
            os.write(10);
            os.flush();
            this.txtChatting.append("\n" + sender + ": " + txtMessage.getText());
            txtMessage.setText("");

        } catch (IOException e) {
            error(e.getMessage());
        }

    }//GEN-LAST:event_btnSendActionPerformed

    private void btnSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFileActionPerformed
        // TODO add your handling code here:
        String sourceFile = txtSourceFile.getText();
        if (sourceFile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please choose a file, Sir!");
            return;
        }

        try {
            FileReader fr = new FileReader(sourceFile);
            BufferedReader bf = new BufferedReader(fr);
            String line = "";
            // send file
            int pos = sourceFile.lastIndexOf("\\");
            String fileName = sourceFile.substring(pos + 1);
            // name of file
            os.writeBytes(fileName);
            os.write(13);
            os.write(10);
            os.flush();
            // content
            while ((line = bf.readLine()) != null) {
                os.writeBytes(line);
                os.write(13);
                os.write(10);
                os.flush();
            }
            // end of file
            os.writeBytes("EndFile*$#");
            os.write(13);
            os.write(10);
            os.flush();
            bf.close();
            fr.close();
            txtSourceFile.setText("");

        } catch (IOException e) {
            error(e.getMessage());
        }

    }//GEN-LAST:event_btnSendFileActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int value = fileChooser.showOpenDialog(this);
        if (value == JFileChooser.OPEN_DIALOG) {
            File f = fileChooser.getSelectedFile();
            int pos = f.getName().indexOf(".");
            if (!f.getName().substring(pos).equals(".txt")) {
                JOptionPane.showMessageDialog(fileChooser, "Please only send text file");

            } else {
                txtSourceFile.setText(f.getPath());
            }
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
        if (!txtMessage.getText().isEmpty()) {
            btnSendActionPerformed(evt);
        }
    }//GEN-LAST:event_txtMessageActionPerformed

    private void txtSourceFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSourceFileActionPerformed
        // TODO add your handling code here:
        if (!txtSourceFile.getText().isEmpty()) {
            btnSendFileActionPerformed(evt);
        }
    }//GEN-LAST:event_txtSourceFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel1;
    private javax.swing.JPanel PanelMessage;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtChatting;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtSourceFile;
    // End of variables declaration//GEN-END:variables
}
